# Copyright 2024 Lockheed Martin Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 18:19


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0003_auto_event-id"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdetail",
            name="supporting_data_sort_order",
            field=models.TextField(blank=True, default=b"[]"),
        ),
    ]
